# Generated by Django 4.2 on 2024-12-23 04:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='mobileImage',
            field=models.ImageField(default='', upload_to=api.models.upload_to_unique),
            preserve_default=False,
        ),
    ]
