# Generated by Django 4.2 on 2024-12-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebanner',
            options={'verbose_name_plural': 'Home Banner'},
        ),
    ]
