# Generated by Django 4.2 on 2024-12-23 16:10

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='images',
        ),
        migrations.AlterField(
            model_name='getinvolved',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_to_unique),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_to_unique),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='mobileImage',
            field=models.ImageField(upload_to=api.models.upload_to_unique),
        ),
        migrations.AlterField(
            model_name='howitsgoing',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_to_unique),
        ),
        migrations.AlterField(
            model_name='howitstarted',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_to_unique),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_to_unique),
        ),
        migrations.AlterField(
            model_name='ourvalues',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_to_unique),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_to_unique),
        ),
        migrations.AlterField(
            model_name='whatweoffer',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_to_unique),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_to_unique),
        ),
        migrations.CreateModel(
            name='ActivityImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.upload_to_unique)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.activity')),
            ],
        ),
    ]
