# Generated by Django 4.2 on 2024-12-23 05:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_homebanner_mobileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='activity',
            name='thumbnail_image',
            field=models.ImageField(default='', upload_to=api.models.upload_to_unique),
            preserve_default=False,
        ),
    ]
