# Generated by Django 4.2 on 2024-12-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_activity_description_alter_activity_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
