# Generated by Django 4.2 on 2024-12-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_activity_thumbnail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='images',
        ),
    ]
