# Generated by Django 5.1.4 on 2025-01-07 12:32

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_activity_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='howitstarted',
            options={'verbose_name_plural': 'Our Story'},
        ),
        migrations.AlterModelOptions(
            name='whatwedo',
            options={'verbose_name_plural': 'Thematic Areas'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='howitstarted',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
